runtime: java11
instance_class: F1

handlers:
- url: /.*
  script: auto

env_variables:
  # DÁN GIÁ TRỊ VÀO ĐÂY
  INSTANCE_CONNECTION_NAME: 'food-ordering-db-instance'
  
  # Điền các thông tin còn lại của CSDL bạn đã tạo
  DB_NAME: 'food_ordering_db'  # Hoặc tên database bạn đã đặt
  DB_USER: 'postgres'          # User mặc định của Cloud SQL PostgreSQL
  DB_PASS: '1234'  # Mật khẩu bạn đã tạo khi khởi tạo instance
